### ISSUE TITLE
Make URI more resultful

### ISSUE THREAD

**Issue by yyc1217** [NCU-CC/Location-Service#16]
Current | Improvement | Remark
------------ | ------------- | -------------
GET /keyword/{keyword} | GET /?q=keyword1&limit=10 | query parameter <br> at least 1 keyword <br> limit
GET /unit/name/{unitName} | GET /unit/{unitName} | 
GET /place/name/{buildingName}/units | GET /unit?building={buildingName} | query parameter
GET /person/name/{employeeName} | GET /faculty/{facultyName} | 
GET /place/type/{placeType} | GET /place?type={placeType} | query parameter
GET /place/name/{name} | GET /place?name={name} | query parameter

Just a recommendation...

**Comment by jason1122g** [comment]
this will be implemented in next release

**Comment by yyc1217** [comment]
Current | Improvement | Remark
------------ | ------------- | -------------
GET /keyword/{keyword} | GET /place/search?q=keyword1&limit=10 | query parameter: <br> at least 1 keyword <br> limit
GET /unit/name/{unitName} | GET /unit/{unitName} | 
GET /place/name/{buildingName}/units | GET /unit?building={buildingName} | query parameter
GET /person/name/{employeeName} | GET /faculty/{facultyName} | 
GET /place/type/{placeType} | GET /place?type={placeType} | query parameter
GET /place/name/{name} | GET /place?name={name} | query parameter

modified.

**Comment by yyc1217** [comment]
NCU-CC/API-Documentation/pull/4

**Comment by jason1122g** [comment]
#20
